server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xon
    username: xon9798
    password: 9798
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
      enabled: true
upload:
  server:
    folder: D:/
api:
  jsonplaceholder: https://jsonplaceholder.typicode.com
url:
  jsonplachoder: https://jsonplaceholder.typicode.com/