server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/xon
    username: xon9798
    password: 9798
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: update